/* eslint-disable react/jsx-props-no-spreading */
import React, { useEffect } from 'react';
import '../styles/globals.css';
import Head from 'next/head';
import PropTypes from 'prop-types';
import { useDispatch } from 'react-redux';
import Toolbar from '../components/Toolbar';
import wrapper from '../configure/configure';
import { LOAD_MY_INFO_REQUEST } from '../reducers/user';

function MyApp({ Component, pageProps }) {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch({
      type: LOAD_MY_INFO_REQUEST,
    });
    // dispatch({
    //   type: LOAD_POSTS_REQUEST,
    // });
  }, []);

  return (
    <>
      <Head>
        <title>NEXT 게시판</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet" />
      </Head>
      <Toolbar />
      <Component {...pageProps} />
    </>
  );
}

MyApp.propTypes = {
  Component: PropTypes.elementType.isRequired,
  pageProps: PropTypes.object.isRequired,
};

export default wrapper.withRedux(MyApp);
